"""The submission fingerprint's `dirty` flag (bench/_machine.py): the suite's own
outputs must not count as contributor edits. Pure string/glob logic, off-device."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "bench"))
import _machine as m   # noqa: E402


class TestIsSuiteOutput:
  """Which paths the suite rewrites as part of running."""

  def test_perf_step_outputs_are_suite_writes(self):
    # every result_file in roofline_suite.py's PERF_FAST / PERF_FULL tables
    for name in ("device_saturation_sweep_results.json",
                 "device_bandwidth_roofline_results.json",
                 "device_serving_sweep_results.json",
                 "decode_measurement_results.json",
                 "device_compare_wattcomplete_results.json",
                 "roofline_analysis_results.json",
                 "numeric_cliffs_results.json"):
      assert m._is_suite_output(f"bench/results/{name}"), name

  def test_committed_submissions_are_not_suite_writes(self):
    # a contributor's datapoint is a real addition and SHOULD show up as a change
    assert not m._is_suite_output(
      "bench/results/rooflines/roofline-apple-m2-pro-Mac14_12-723396ad9091-44d76599.json")

  def test_generated_table_is_not_a_suite_write(self):
    # ROOFLINES.md is regenerated by the contributor, not by --perf
    assert not m._is_suite_output("bench/results/ROOFLINES.md")

  def test_source_edits_are_not_suite_writes(self):
    for p in ("bench/_machine.py", "aneforge/_compile.py", "tests/test_shapes.py",
              "bench/results/README.md"):
      assert not m._is_suite_output(p), p

  def test_similarly_named_paths_outside_results_are_not_matched(self):
    # the glob is anchored to bench/results/, not any *_results.json anywhere
    assert not m._is_suite_output("decode_measurement_results.json")
    assert not m._is_suite_output("bench/decode_measurement_results.json")
    assert not m._is_suite_output("bench/results/nested/decode_measurement_results.json")


class TestPorcelainPaths:
  """Parsing `git status --porcelain` v1 output."""

  def test_modified_and_untracked(self):
    status = " M bench/results/decode_measurement_results.json\n?? bench/results/rooflines/new.json"
    assert m._porcelain_paths(status) == [
      "bench/results/decode_measurement_results.json",
      "bench/results/rooflines/new.json",
    ]

  def test_staged_and_index_states(self):
    # 'A  path' (added), 'MM path' (staged+unstaged), 'D  path' (deleted)
    status = "A  bench/new.py\nMM aneforge/graph.py\nD  docs/old.md"
    assert m._porcelain_paths(status) == ["bench/new.py", "aneforge/graph.py", "docs/old.md"]

  def test_rename_scores_the_destination(self):
    status = "R  bench/old_name.py -> bench/new_name.py"
    assert m._porcelain_paths(status) == ["bench/new_name.py"]

  def test_quoted_path_with_spaces(self):
    status = ' M "bench/results/a file.json"'
    assert m._porcelain_paths(status) == ["bench/results/a file.json"]

  def test_empty_and_blank_lines(self):
    assert m._porcelain_paths("") == []
    assert m._porcelain_paths("\n\n") == []

  def test_first_line_survives_the_stripped_leading_space(self):
    # _git() strips the whole stdout, so a leading ' M' arrives as 'M' and a fixed
    # line[3:] offset would eat a character: bench/... -> ench/...
    stripped = "M bench/results/decode_measurement_results.json\n M bench/results/other_results.json"
    assert m._porcelain_paths(stripped) == [
      "bench/results/decode_measurement_results.json",
      "bench/results/other_results.json",
    ]


class TestDirtyDecision:
  """The composed rule: dirty iff a non-suite-output path changed."""

  def _dirty(self, status):
    """Mirror _git_info()'s decision without shelling out to git."""
    return bool([p for p in m._porcelain_paths(status) if not m._is_suite_output(p)])

  def test_clean_tree_is_not_dirty(self):
    assert self._dirty("") is False

  def test_suite_outputs_alone_are_not_dirty(self):
    # THE REGRESSION: this is what --perf leaves behind on a pristine checkout.
    # First line has no leading space, matching what _git()'s strip() produces.
    status = ("M bench/results/device_saturation_sweep_results.json\n"
              " M bench/results/device_bandwidth_roofline_results.json\n"
              " M bench/results/decode_measurement_results.json\n"
              " M bench/results/roofline_analysis_results.json")
    assert self._dirty(status) is False

  def test_real_source_edit_is_dirty(self):
    assert self._dirty(" M bench/decode_measurement.py") is True

  def test_source_edit_alongside_suite_outputs_is_dirty(self):
    # a contributor hacking on the benchmark must still be flagged
    status = (" M bench/results/decode_measurement_results.json\n"
              " M bench/decode_measurement.py")
    assert self._dirty(status) is True

  def test_new_submission_json_is_dirty(self):
    # the suite writes its own fingerprinted JSON last; it is untracked at fingerprint
    # time, and unlike the *_results.json files it is the artifact being contributed,
    # so it legitimately marks the tree as changed
    assert self._dirty("?? bench/results/rooflines/roofline-apple-m2-pro-x-y.json") is True
