#!/usr/bin/env python3
"""Aggregate every committed roofline submission into one browsable table.

Contributors run bench/roofline_suite.py, which drops a fingerprinted JSON into
bench/results/rooflines/. This walks that directory, groups submissions by
hardware_hash (so genuinely-identical machines pool, while an M2 Air and an M2
Mac mini stay separate), and renders bench/results/ROOFLINES.md - a table GitHub
displays inline, so "look at the accumulated results" is just opening that file.

ROOFLINES.md is GENERATED. A PR that adds a submission must regenerate it; CI
runs this with --check and fails the PR if the committed table is stale, so the
table can never drift from the data (no bot commits, no write tokens needed).

  python3 bench/aggregate_rooflines.py            # (re)write bench/results/ROOFLINES.md
  python3 bench/aggregate_rooflines.py --check     # exit 1 if the committed table is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ROOFLINES_DIR = REPO / "bench" / "results" / "rooflines"
TABLE = REPO / "bench" / "results" / "ROOFLINES.md"
# Machine-readable twin of the headline table. Generated and CI-checked alongside ROOFLINES.md,
# so anything that can read it (e.g. the Hugging Face leaderboard Space, which fetches it from
# raw.githubusercontent.com) tracks main automatically as datapoints land.
HEADLINE_JSON = REPO / "bench" / "results" / "rooflines.json"

MARKER = "<!-- generated by bench/aggregate_rooflines.py; do not edit by hand -->"

# Decode tok/s is only comparable across machines when every row measured the SAME model.
# decode_measurement.py's default (--perf) uses this config; its --perf-full mode swaps in a
# ~4x heavier model (2048 dim / 8 layers), whose tok/s is a valid but incomparable number.
# The headline column only accepts a submission whose decode config matches this one; an
# off-config submission's decode is dropped (blank), not shown next to the canonical rows.
CANONICAL_DECODE_CONFIG = {"d_model": 1024, "n_layers": 4, "n_heads": 16,
                           "d_head": 64, "d_ff": 4096, "vocab": 32000, "s_kv": 128}


def _load() -> list[dict]:
    reports = []
    for p in sorted(ROOFLINES_DIR.glob("roofline-*.json")):
        try:
            reports.append(json.loads(p.read_text()))
        except Exception as e:
            print(f"warning: skipping unreadable {p.name}: {e}", file=sys.stderr)
    return reports


def _group(reports: list[dict]) -> dict[str, dict]:
    """Group by hardware_hash; keep every submission, pick the latest as representative."""
    groups: dict[str, dict] = {}
    for r in reports:
        h = r.get("machine", {}).get("hardware_hash", "unknown")
        g = groups.setdefault(h, {"submissions": []})
        g["submissions"].append(r)
    for g in groups.values():
        g["submissions"].sort(key=lambda r: r["machine"]["environment"].get("timestamp_utc", ""))
        g["latest"] = g["submissions"][-1]
    return groups


def _fmt_cliff(nc: dict) -> tuple[str, str, str]:
    """(matmul, slice, reduce) cliff cells for one submission's numeric plane."""
    if not nc:
        return ("-", "-", "-")
    mm = nc.get("matmul_saturation", {}).get("by_K", [{}])
    mm_val = mm[0].get("cliff") if mm else None
    matmul = f"~{mm_val:.0f}" if isinstance(mm_val, (int, float)) else "n/a"
    sl = nc.get("slice_saturation", {}).get("cliff")
    slice_cell = "exact (no clamp)" if sl is None else f"clamp @ {sl:.0f}"
    rex = nc.get("reduce_exactness", {}).get("last_all_exact")
    reduce_cell = f"<= {rex}" if rex is not None else "n/a"
    return (matmul, slice_cell, reduce_cell)


def _power_label(pw: dict) -> str:
    """Compact power cell: source (+ battery %) + Energy Mode when non-default.

    High Power / Low Power materially change perf, so they are shown; 'automatic'
    (the default) is omitted for brevity but is always in the JSON."""
    src = pw.get("source", "?")
    if pw.get("is_laptop") and pw.get("source") == "battery":
        src += f" {pw.get('battery_pct')}%"
    mode = (pw.get("energy_mode") or {}).get("mode")
    if mode and mode != "automatic":
        src += f" ({mode.replace('_', '-')})"
    return src


def _perf_summary(report: dict, script: str) -> dict | None:
    """The embedded summary JSON of one perf script in a submission, if it ran clean."""
    for e in (report.get("perf_rooflines") or []):
        if e.get("script") == script and e.get("returncode") == 0:
            return e.get("summary")
    return None


def _perf_headline(report: dict) -> dict:
    """A few headline ANE numbers pulled from a submission's perf_rooflines.

    Full detail (per-size sweeps, all engines, watts) stays in the JSON; this is
    just the marquee set for the table. Every field is best-effort -> None.

    Prefers roofline_analysis's synthesis, but falls back to the raw saturation +
    bandwidth sweeps for GEMM / bandwidth / ridge when it is absent or errored --
    e.g. a submission from before #147, where roofline_analysis KeyError'd on a
    device a sweep could not measure. The raw sweeps carry the same ANE peaks, so
    the headline still fills instead of showing three blanks."""
    h: dict = {"gemm_tflops": None, "bw_gbps": None, "ridge": None,
               "perf_per_w": None, "decode_tok_s": None, "decode_blocked": False,
               "decode_offconfig": False}
    ra = _perf_summary(report, "roofline_analysis.py")
    if ra:
        ceil = ra.get("ceilings") or {}
        ane = (ceil.get("compute") or {}).get("ANE") or {}
        g = ane.get("gemm_peak_gflops")
        h["gemm_tflops"] = g / 1000.0 if isinstance(g, (int, float)) else None
        h["bw_gbps"] = (ceil.get("bandwidth_gbps") or {}).get("ANE")
        h["ridge"] = (ceil.get("ridge_flop_per_byte") or {}).get("ANE")
    sat = _perf_summary(report, "device_saturation_sweep.py")
    gane = (((sat or {}).get("peaks") or {}).get("gemm") or {}).get("ANE") or {}
    h["perf_per_w"] = gane.get("peak_perf_per_W")
    if h["gemm_tflops"] is None and isinstance(gane.get("peak_gflops"), (int, float)):
        h["gemm_tflops"] = gane["peak_gflops"] / 1000.0
    if h["bw_gbps"] is None:
        bw = _perf_summary(report, "device_bandwidth_roofline.py") or {}
        strm = ((bw.get("results") or {}).get("roofline") or {}).get("streaming (relu / x*2)", {})
        h["bw_gbps"] = ((strm.get("peak") or {}).get("ane") or {}).get("gbps")
    if h["ridge"] is None and h["gemm_tflops"] and h["bw_gbps"]:
        h["ridge"] = h["gemm_tflops"] * 1000.0 / h["bw_gbps"]
    dm = _perf_summary(report, "decode_measurement.py")
    if dm:
        b1 = next((r for r in (dm.get("rows") or [])
                   if r.get("device") == "ANE" and r.get("batch") == 1), None)
        if b1:
            h["decode_tok_s"] = b1.get("tokens_per_s")
            # decode ran but the ANE could not: e.g. the 32000-vocab lm_head exceeds an
            # older family's matmul-dim limit. Distinguish that from "not measured".
            if h["decode_tok_s"] is None and b1.get("status") not in (None, "ok"):
                h["decode_blocked"] = True
            # off-config (a --perf-full submission ran a heavier model): a real but incomparable tok/s
            if h["decode_tok_s"] is not None and dm.get("config") != CANONICAL_DECODE_CONFIG:
                h["decode_tok_s"] = None
                h["decode_offconfig"] = True
    return h


def render(reports: list[dict]) -> str:
    groups = _group(reports)
    n_machines = len(groups)
    n_subs = sum(len(g["submissions"]) for g in groups.values())
    lines = [
        MARKER,
        "# ANE roofline results",
        "",
        f"Accumulated across **{n_machines} machine(s)**, {n_subs} submission(s). "
        "Each row is a distinct machine (grouped by hardware hash; identical silicon in "
        "different chassis stays separate by model identifier).",
        "",
        "Add yours: `PYTHONPATH=. python3 bench/roofline_suite.py --contributor <your-gh-handle>`, "
        "commit the JSON it writes under `bench/results/rooflines/`, regenerate this file with "
        "`python3 bench/aggregate_rooflines.py`, and open a PR. See "
        "[`rooflines/README.md`](rooflines/README.md).",
        "",
    ]
    handles = sorted({c for c in (r.get("contributor") for r in reports) if c})
    if handles:
        lines += ["Thanks to " + ", ".join(f"[@{h}](https://github.com/{h})" for h in handles)
                  + " for contributing datapoints.", ""]

    # --- Machines ---
    lines += [
        "## Machines",
        "",
        "| Chip | Model | CPU (P+E) | GPU | Memory | macOS | Power | Code (main merge-base) | By | Runs |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for _, g in sorted(groups.items(), key=lambda kv: str(kv[1]["latest"]["machine"]["hardware"].get("chip"))):
        hw = g["latest"]["machine"]["hardware"]
        env = g["latest"]["machine"]["environment"]
        git = env.get("aneforge_git", {})
        mainrel = (git.get("main") or {})
        base = mainrel.get("merge_base_short") or (git.get("short") or "?")
        drift = []
        if git.get("dirty"):
            drift.append("dirty")
        if mainrel.get("commits_ahead"):
            drift.append(f"+{mainrel['commits_ahead']}")
        if mainrel.get("commits_behind"):
            drift.append(f"-{mainrel['commits_behind']}")
        code = base + (f" ({', '.join(drift)})" if drift else "")
        power = _power_label(env.get("power", {}))
        mem = f"{hw.get('ram_gb')} GB {hw.get('memory_architecture','')}".strip()
        # credit the most recent submission that named a contributor
        handle = next((r.get("contributor") for r in reversed(g["submissions"]) if r.get("contributor")), None)
        by = f"[@{handle}](https://github.com/{handle})" if handle else "-"
        lines.append(
            f"| {hw.get('chip','?')} | {hw.get('model_identifier','?')} "
            f"| {hw.get('p_cores','?')}+{hw.get('e_cores','?')} | {hw.get('gpu_cores','?')} "
            f"| {mem} | {env.get('macos_version','?')} ({env.get('macos_build','?')}) "
            f"| {power} | {code} | {by} | {len(g['submissions'])} |"
        )

    # --- Numeric cliffs (the cross-silicon correctness rooflines) ---
    lines += [
        "",
        "## Numeric cliffs (correctness rooflines)",
        "",
        "Where fp16 math on the engine silently goes wrong (issue #115, "
        "docs/cross-chip.md). These are magnitude thresholds, independent of clock, "
        "so they are valid even on battery.",
        "",
        "| Chip | Model | matmul inf-cliff | slice-x16 (Q.4 crop-DMA) | reduce exact-sum |",
        "| --- | --- | --- | --- | --- |",
    ]
    for _, g in sorted(groups.items(), key=lambda kv: str(kv[1]["latest"]["machine"]["hardware"].get("chip"))):
        hw = g["latest"]["machine"]["hardware"]
        matmul, slice_cell, reduce_cell = _fmt_cliff(g["latest"].get("numeric_cliffs"))
        lines.append(
            f"| {hw.get('chip','?')} | {hw.get('model_identifier','?')} "
            f"| {matmul} | {slice_cell} | {reduce_cell} |"
        )
    lines += [
        "",
        "_matmul: output magnitude that flips finite->inf (~fp16_max/2). "
        "slice: the pre-A16 crop-DMA clamps |value|>4094; 'exact' means the clamp is "
        "gone (A16/M5). reduce: largest all-exact integer row-sum (fp16 grid coarsens past 2048)._",
        "",
    ]

    # --- Performance rooflines (headline) ---
    perf_rows = []
    any_decode_blocked = False
    offconfig_chips = []
    for _, g in sorted(groups.items(), key=lambda kv: str(kv[1]["latest"]["machine"]["hardware"].get("chip"))):
        # use the most recent submission that carries perf data
        sub = next((r for r in reversed(g["submissions"]) if r.get("perf_rooflines")), None)
        if not sub:
            continue
        h = _perf_headline(sub)
        if not any(v is not None for v in h.values()):
            continue
        hw = sub["machine"]["hardware"]
        power = _power_label(sub["machine"]["environment"].get("power", {}))

        def _c(v, fmt):
            return format(v, fmt) if isinstance(v, (int, float)) else "-"
        # decode: a number if it ran, "n/a" if the ANE could not run it (dim limit),
        # "-" if simply not measured.
        decode = _c(h["decode_tok_s"], ".0f")
        if h["decode_tok_s"] is None and h.get("decode_blocked"):
            decode = "n/a"
            any_decode_blocked = True
        elif h.get("decode_offconfig"):
            offconfig_chips.append(hw.get("chip", "?"))
        perf_rows.append(
            f"| {hw.get('chip','?')} | {hw.get('model_identifier','?')} "
            f"| {_c(h['gemm_tflops'], '.1f')} | {_c(h['bw_gbps'], '.2g')} "
            f"| {_c(h['ridge'], '.0f')} | {_c(h['perf_per_w'], '.0f')} "
            f"| {decode} | {power} |"
        )

    lines += ["## Performance rooflines (headline)", ""]
    if perf_rows:
        lines += [
            "Peak ANE numbers only; the full per-size sweeps, all-engine comparison, "
            "and per-rail watts live in each machine's JSON under `perf_rooflines`. "
            "Perf depends on power/thermals, so the state is shown per row.",
            "",
            "**Peak fp16 GEMM (TF/s)** is the headline compute number -- measured directly on every "
            "machine and the most robust cross-chip comparison. Bandwidth/ridge come from the streaming "
            "sweep and are more dispatch-overhead-sensitive on smaller/older parts, so read them as "
            "indicative. Decode is migrating to a tiled vocab head (#181); see the note under the table.",
            "",
            "| Chip | Model | Peak fp16 GEMM (TF/s) | Bandwidth (GB/s) | Ridge (FLOP/byte) | Peak perf/W (GF/s/W) | Decode @b1 (tok/s) | Power |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
            *perf_rows,
            "",
        ]
        if any_decode_blocked:
            lines += [
                "_`n/a` decode = a stale datapoint from before the tiled vocab head (#181). The old "
                "untiled 32000-vocab lm_head exceeds the 16384 max matmul dimension on the A13-A15 "
                "families, so only A16+ (M5) reported. The tiled head fixes this; the older machines "
                "re-run to populate it. Until then, use **Peak fp16 GEMM (TF/s)** as the headline._",
                "",
            ]
        if offconfig_chips:
            chips = ", ".join(sorted(set(offconfig_chips)))
            lines += [
                f"_Blank decode ({chips}): the submission measured decode with `--perf-full`, whose "
                "model is ~4x heavier than the canonical `--perf` model, so its tok/s is real but not "
                "comparable to the other rows. It is dropped from this column rather than ranked against "
                "a different model; re-run decode in the default (`--perf`) mode to populate it._",
                "",
            ]
    else:
        lines += ["_No `--perf` submissions yet. Run on AC power with "
                  "`python3 bench/roofline_suite.py --perf` (needs sudo for watts)._", ""]
    return "\n".join(lines)


def _num(v, nd):
    return round(v, nd) if isinstance(v, (int, float)) else None


def build_headline_json(reports: list[dict]) -> list[dict]:
    """The headline table as one record per machine -- the same numbers ROOFLINES.md shows, but
    machine-readable (field names match the columns). Perf comes from the latest perf-bearing
    submission, cliffs and identity from the group's latest, exactly as render() does."""
    groups = _group(reports)
    rows = []
    for _, g in sorted(groups.items(), key=lambda kv: str(kv[1]["latest"]["machine"]["hardware"].get("chip"))):
        hw = g["latest"]["machine"]["hardware"]
        matmul, slice_cell, reduce_cell = _fmt_cliff(g["latest"].get("numeric_cliffs"))
        sub = next((r for r in reversed(g["submissions"]) if r.get("perf_rooflines")), None) or g["latest"]
        h = _perf_headline(sub)
        env = sub["machine"]["environment"]
        handle = next((r.get("contributor") for r in reversed(g["submissions"]) if r.get("contributor")), None)
        rows.append({
            "chip": hw.get("chip"),
            "model_identifier": hw.get("model_identifier"),
            "hardware_hash": sub["machine"].get("hardware_hash"),
            "p_cores": hw.get("p_cores"),
            "e_cores": hw.get("e_cores"),
            "gpu_cores": hw.get("gpu_cores"),
            "ram_gb": hw.get("ram_gb"),
            "macos_version": env.get("macos_version"),
            "macos_build": env.get("macos_build"),
            "aneforge_version": env.get("aneforge_version"),
            "power": _power_label(env.get("power", {})),
            "contributor": handle,
            "peak_fp16_gemm_tflops": _num(h.get("gemm_tflops"), 2),
            "bandwidth_gbps": _num(h.get("bw_gbps"), 2),
            "ridge_flop_per_byte": _num(h.get("ridge"), 0),
            "peak_perf_per_w_gflops": _num(h.get("perf_per_w"), 0),
            "decode_tok_s": _num(h.get("decode_tok_s"), 0),
            "matmul_inf_cliff": matmul,
            "slice_x16_cliff": slice_cell,
            "reduce_exact_sum": reduce_cell,
            "timestamp_utc": env.get("timestamp_utc"),
        })
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed ROOFLINES.md / rooflines.json differ from freshly generated")
    args = ap.parse_args()

    reports = _load()
    fresh = render(reports)
    fresh_json = json.dumps(build_headline_json(reports), indent=2)

    if args.check:
        stale = []
        if (TABLE.read_text().strip() if TABLE.exists() else "") != fresh.strip():
            stale.append("ROOFLINES.md")
        if (HEADLINE_JSON.read_text().strip() if HEADLINE_JSON.exists() else "") != fresh_json.strip():
            stale.append("rooflines.json")
        if stale:
            print(f"{' and '.join(stale)} stale. Run: python3 bench/aggregate_rooflines.py", file=sys.stderr)
            return 1
        print(f"ROOFLINES.md + rooflines.json up to date ({len(reports)} submission(s)).")
        return 0

    TABLE.write_text(fresh + "\n")
    HEADLINE_JSON.write_text(fresh_json + "\n")
    print(f"wrote {TABLE.relative_to(REPO)} + {HEADLINE_JSON.relative_to(REPO)} "
          f"from {len(reports)} submission(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
